# Copyright (C) 2017 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU LGPL v2.1 or later

language: cpp

# for recent abi-compliance-checker
dist: trusty

script:
  - cd cpptest
  - ./autogen.sh
  - ./configure --enable-doc
  - make
  - make check
  - make distcheck
  - ./check-abi.sh

addons:
  apt:
    packages:
    - abi-compliance-checker
    - doxygen
